import { ROLES } from './roles.js';

export const PERMISSIONS = {
  // Regions
  REGIONS_READ: 'regions:read',
  REGIONS_WRITE: 'regions:write',
  REGIONS_DELETE: 'regions:delete',
  // Schools
  SCHOOLS_READ: 'schools:read',
  SCHOOLS_WRITE: 'schools:write',
  SCHOOLS_DELETE: 'schools:delete',
  // Teams
  TEAMS_READ: 'teams:read',
  TEAMS_WRITE: 'teams:write',
  TEAMS_DELETE: 'teams:delete',
  // Workers
  WORKERS_READ: 'workers:read',
  WORKERS_WRITE: 'workers:write',
  WORKERS_DELETE: 'workers:delete',
  // Categories
  CATEGORIES_READ: 'categories:read',
  CATEGORIES_WRITE: 'categories:write',
  // Tickets
  TICKETS_READ: 'tickets:read',
  TICKETS_CREATE: 'tickets:create',
  TICKETS_ASSIGN: 'tickets:assign',
  TICKETS_UPDATE: 'tickets:update',
  TICKETS_REVIEW: 'tickets:review',
  TICKETS_CLOSE: 'tickets:close',
  // Tasks
  TASKS_READ: 'tasks:read',
  TASKS_ACCEPT: 'tasks:accept',
  TASKS_WORK: 'tasks:work',
  TASKS_COMPLETE: 'tasks:complete',
  // Inventory
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  INVENTORY_APPROVE: 'inventory:approve',
  MATERIAL_REQUESTS_READ: 'material_requests:read',
  MATERIAL_REQUESTS_CREATE: 'material_requests:create',
  // Reports
  REPORTS_READ: 'reports:read',
  REPORTS_GENERATE: 'reports:generate',
  // Dashboard
  DASHBOARD_ADMIN: 'dashboard:admin',
  DASHBOARD_LEADER: 'dashboard:leader',
  DASHBOARD_WORKER: 'dashboard:worker',
  DASHBOARD_SCHOOL: 'dashboard:school',
  // Audit
  AUDIT_READ: 'audit:read',
  // SLA
  SLA_READ: 'sla:read',
  SLA_WRITE: 'sla:write',
  // Users
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  // Assets
  ASSETS_READ: 'assets:read',
  ASSETS_WRITE: 'assets:write',
  // Preventive
  PREVENTIVE_READ: 'preventive:read',
  PREVENTIVE_WRITE: 'preventive:write',
};

const ALL = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ALL,
  [ROLES.MAINTENANCE_MANAGER]: [
    PERMISSIONS.REGIONS_READ,
    PERMISSIONS.SCHOOLS_READ,
    PERMISSIONS.SCHOOLS_WRITE,
    PERMISSIONS.TEAMS_READ,
    PERMISSIONS.TEAMS_WRITE,
    PERMISSIONS.WORKERS_READ,
    PERMISSIONS.WORKERS_WRITE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.CATEGORIES_WRITE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_UPDATE,
    PERMISSIONS.TICKETS_REVIEW,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.INVENTORY_APPROVE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SLA_READ,
    PERMISSIONS.SLA_WRITE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.ASSETS_WRITE,
    PERMISSIONS.PREVENTIVE_READ,
    PERMISSIONS.PREVENTIVE_WRITE,
  ],
  [ROLES.TEAM_LEADER]: [
    PERMISSIONS.SCHOOLS_READ,
    PERMISSIONS.TEAMS_READ,
    PERMISSIONS.WORKERS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_UPDATE,
    PERMISSIONS.TICKETS_REVIEW,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.MATERIAL_REQUESTS_READ,
    PERMISSIONS.MATERIAL_REQUESTS_CREATE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.DASHBOARD_LEADER,
    PERMISSIONS.ASSETS_READ,
  ],
  [ROLES.WORKER]: [
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.TASKS_ACCEPT,
    PERMISSIONS.TASKS_WORK,
    PERMISSIONS.TASKS_COMPLETE,
    PERMISSIONS.MATERIAL_REQUESTS_READ,
    PERMISSIONS.MATERIAL_REQUESTS_CREATE,
    PERMISSIONS.DASHBOARD_WORKER,
  ],
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.DASHBOARD_SCHOOL,
  ],
  [ROLES.WAREHOUSE_KEEPER]: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.INVENTORY_APPROVE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TASKS_READ,
  ],
};

export function getPermissionsForRoles(roles) {
  const perms = new Set();
  for (const role of roles) {
    (ROLE_PERMISSIONS[role] || []).forEach((p) => perms.add(p));
  }
  return [...perms];
}
